export {
  createTailwindV4CompiledSourceEntries,
  createTailwindV4DefaultIgnoreSources,
  createTailwindV4RootSources,
  createTailwindV4SourceEntryMatcher,
  createTailwindV4SourceExclusionMatcher,
  expandTailwindV4SourceEntries,
  expandTailwindV4SourceEntryBraces,
  groupTailwindV4SourceEntriesByBase,
  isFileExcludedByTailwindV4SourceEntries,
  isFileMatchedByTailwindV4SourceEntries,
  mergeTailwindV4SourceEntries,
  normalizeGlobPattern,
  normalizeTailwindV4ScannerSources,
  normalizeTailwindV4SourceEntries,
  resolveSourceScanPath,
  resolveTailwindV4SourceBaseCandidates,
  resolveTailwindV4SourceEntry,
  TAILWIND_V4_AUTO_SOURCE_SCAN_PATTERN,
  TAILWIND_V4_IGNORED_CONTENT_DIRS,
  TAILWIND_V4_IGNORED_EXTENSIONS,
  TAILWIND_V4_IGNORED_FILES,
  toPosixPath,
} from '@tailwindcss-mangle/engine/v4/source-scan'
