export type {
  TailwindV4CandidateSource,
  TailwindV4CompiledSourceRoot,
  TailwindV4CssSource,
  TailwindV4DesignSystem,
  TailwindV4Engine,
  TailwindV4GenerateOptions,
  TailwindV4GenerateResult,
  TailwindV4ResolvedSource,
  TailwindV4SourceOptions,
  TailwindV4SourcePattern,
  TailwindV4StyleGenerateOptions,
  TailwindV4StyleGenerateResult,
  TailwindV4StyleSource,
} from '@tailwindcss-mangle/engine/v4/types'
