packages:
  - packages/*
  - scripts/*
  - website
  - apps/*
  - templates/*
  - '!**/test/**'
shamefullyHoist: true
gitChecks: false
hoistPattern:
  - '!tailwindcss'
packageManagerStrict: false
publicHoistPattern:
  - '*@nextui-org/*'
allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': true
  core-js: false
  esbuild: true
  msgpackr-extract: false
  sharp: true
  unrs-resolver: false
  workerd: true
  yorkie: false
catalogs:
  tailwindcss2:
    tailwindcss: npm:@tailwindcss/postcss7-compat@^2.2.17
    tailwindcss2: npm:@tailwindcss/postcss7-compat@^2.2.17
  tailwindcss3:
    tailwindcss: ^4.3.2
    tailwindcss-3: npm:tailwindcss@^3.4.19
  tailwindcss4:
    tailwindcss: ^4.3.2
    tailwindcss-4: npm:tailwindcss@^4.3.2
minimumReleaseAge: 0
