/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class NativeCacheState {
  constructor(enabled: boolean, driver: string, context?: string | undefined | null)
  configure(enabled: boolean, context?: string | undefined | null): void
  normalizeIndex(payload: string): string
  prepareWrite(values: Array<string>, parsed: string | undefined | null, now: string): string
  read(parsed?: string | undefined | null): string
  rememberReadMeta(meta: string): void
  getLastReadMeta(): string
  prepareClear(scope: string, parsed: string | undefined | null, now: string): string
  snapshot(parsed?: string | undefined | null): string | null
}

export declare class NativeContext {
  constructor()
  reset(replacements: Array<Replacement>, preserved: Array<string>): void
  update(replacements: Array<Replacement>): void
  setPreserved(preserved: Array<string>): void
  transformJs(source: string, preserveFunctions: Array<string>, splitQuote: boolean): TransformResult
  transformCss(source: string, ignoreVueScoped: boolean): TransformResult
  transformHtml(source: string): TransformResult
  transformSelector(source: string, ignoreVueScoped: boolean): SelectorResult
  transformText(source: string, splitQuote: boolean): TransformResult
}

export declare class NativeRawCandidateCache {
  constructor(limit: number)
  get(key: string, fingerprint: string): RawCandidateCacheEntry | null
  set(key: string, fingerprint: string, candidates: Array<string>): void
}

export interface BareSelectorAlias {
  canonical: string
  candidate: string
}

export declare function buildLineOffsetsNative(content: string): Array<number>

/**
 * A compact visitor-order callback plan, never an AST. The normal transform
 * remains a single native call; this plan is only used for live JS callbacks.
 */
export interface CallbackEvent {
  kind: string
  raw: string
  values: Array<string>
  start: number
  end: number
  mode: string
  loneSurrogates: boolean
}

export interface CallbackPlan {
  events: Array<CallbackEvent>
  valid: boolean
}

export declare function collectWorkspaceConfigFilesNative(root: string, maxDepth: number, names: Array<string>): Promise<string[]>

export interface ConfigSourceMigrationResult {
  changed: boolean
  code: string
  changes: Array<string>
}

export declare function createJsStringStaticRangesNative(content: string): Array<ExtractionRange>

export declare function createRawCandidateFileFingerprintNative(files: Array<string>): Promise<string>

/**
 * Locate actual CSS source-map comments without confusing strings or URLs for
 * annotations. The host adapter loads and composes the referenced third-party map.
 */
export declare function cssSourceMapAnnotationsNative(source: string): Array<Edit>

export declare function dedupeCandidatesNative(candidates: Array<ExtractionCandidate>): Array<ExtractionCandidate>

export declare function defaultClassNameNative(index: number, prefix: string): string

export declare function defaultMangleClassFilterNative(value: string): boolean

export interface Edit {
  start: number
  end: number
  content: string
}

export interface EngineSourceSegment {
  content: string
  start: number
  extension: string
}

export declare function escapeCssClassNameNative(value: string): string

export declare function escapeJsStringNative(value: string): string

/**
 * Apply choices captured at each JS callback, in their original order. Repeated
 * candidates and callbacks which mutate later mappings retain legacy behavior.
 */
export declare function executeLiteralNative(event: CallbackEvent, replacements: Array<Replacement>): Edit | null

export declare function expandSourceEntryBracesNative(sources: Array<NativeSourcePattern>): Array<NativeSourcePattern>

export declare function explainCacheContextMismatchNative(current: string, cached: string): Array<string>

export declare function extractBareArbitraryCandidatesNative(content: string, units: Array<string>): Array<ExtractionCandidate>

export declare function extractCssApplySegmentsNative(source: string): Array<EngineSourceSegment>

export declare function extractInlineSourceCandidatesNative(css: string): InlineSourceCandidates

export interface ExtractionCandidate {
  rawCandidate: string
  start: number
  end: number
}

export interface ExtractionJoinedSegments {
  content: string
  segments: Array<ExtractionSegment>
}

export interface ExtractionLineMeta {
  line: number
  column: number
  lineText: string
}

export interface ExtractionRange {
  start: number
  end: number
}

export interface ExtractionRemappedCandidate {
  rawCandidate: string
  start: number
  end: number
  localStart: number
}

export interface ExtractionSegment {
  content: string
  start: number
  joinedStart?: number
}

export declare function extractSfcSourceSegmentsNative(source: string): SfcSourceSegments

export declare function filterMigrationTargetIndexesNative(files: Array<string>, include: Array<string>, exclude: Array<string>): Array<number>

export declare function filterSourceCandidateIndexesNative(content: string, extension: string, candidates: Array<ExtractionCandidate>, skipHtmlContextChecks?: boolean | undefined | null, ranges?: Array<ExtractionRange> | undefined | null): Array<number>

export declare function findAttributeValueStartNative(source: string, value: string): number

export declare function groupSourceEntriesNative(sources: Array<NativeSourcePattern>): Array<NativeSourceGroup>

export declare function hashStableCacheValueNative(tree: string): string

export interface InlineSourceCandidates {
  included: Array<string>
  excluded: Array<string>
}

export declare function inspectLengthUnitsNative(source: string, variableName: string, units: Array<string>): LengthUnitsInspection

export declare function joinSourceSegmentsNative(segments: Array<ExtractionSegment>): ExtractionJoinedSegments

export interface LengthUnitsInspection {
  found: boolean
  missingUnits: Array<string>
}

export interface LengthUnitsPatchResult {
  code: string
  changed: boolean
  matched: boolean
}

export declare function mergeSourceEntriesNative(sources: Array<NativeSourcePattern>): Array<NativeSourcePattern>

export declare function migrateConfigSourceNative(source: string): ConfigSourceMigrationResult

export interface NativeSourceGroup {
  base: string
  entries: Array<NativeSourcePattern>
}

export interface NativeSourcePattern {
  base: string
  pattern: string
  negated: boolean
}

export interface NativeStaticGlobPrefix {
  prefix: Array<string>
  rest: Array<string>
}

export declare function normalizeGlobPatternNative(pattern: string): string

export declare function patchLengthUnitsNative(source: string, units: Array<string>, variableName?: string | undefined | null): LengthUnitsPatchResult

export declare function patchPostcssPluginNative(source: string, refProperty: string, version: number): PatchResult

export interface PatchResult {
  code: string
  hasPatched: boolean
  matched: boolean
}

export declare function patchReturnContextNative(source: string): PatchResult

export declare function planHtmlNative(source: string): CallbackPlan

export declare function planJsNative(source: string, splitQuote: boolean): CallbackPlan

export declare function planTextNative(source: string, splitQuote: boolean): CallbackPlan

export interface RawCandidateCacheEntry {
  fingerprint: string
  candidates: Array<string>
}

export declare function remapSourceCandidatesNative(segments: Array<ExtractionSegment>, candidates: Array<ExtractionCandidate>): Array<ExtractionRemappedCandidate>

export declare function replaceBareArbitrarySelectorsNative(source: string, values: Array<BareSelectorAlias>): string

export interface Replacement {
  original: string
  replacement: string
}

export declare function resolveBareArbitraryCandidatesNative(candidates: Array<string>, units: Array<string>): Array<string | undefined | null>

export declare function resolveLineMetaNative(content: string, offsets: Array<number | undefined | null>, index: number): ExtractionLineMeta

export declare function resolveLineMetasNative(content: string, positions: Array<number>): Array<ExtractionLineMeta>

export declare function restoreConfigEntriesNative(entries: Array<RestoreEntry>, dryRun: boolean): Promise<RestoreResult>

export interface RestoreEntry {
  file?: string
  backupFile?: string
}

export interface RestoreResult {
  scannedEntries: number
  restorableEntries: number
  restoredFiles: number
  missingBackups: number
  skippedEntries: number
  restored: Array<string>
}

export interface RestoreWrite {
  file: string
  source: string
}

export declare function rollbackMigrationWritesNative(entries: Array<RestoreWrite>): Promise<number[]>

export interface SelectorResult {
  code: string
  preserveCount: number
  valid: boolean
}

export interface SfcSourceSegments {
  html: Array<EngineSourceSegment>
  bound: Array<EngineSourceSegment>
  scripts: Array<EngineSourceSegment>
  styles: Array<EngineSourceSegment>
  templates: Array<EngineSourceSegment>
}

export declare function splitCandidateTokensNative(code: string): Array<string>

export declare function splitCodeNative(source: string, splitQuote: boolean): Array<string>

export declare function splitStaticGlobPrefixNative(pattern: string): NativeStaticGlobPrefix

export declare function stripCompiledSourceEntriesNative(source: string): StrippedSourceEntries

export declare function stripEscapeSequenceNative(value: string): string

export interface StrippedSourceEntries {
  css: string
  changed: boolean
}

export interface TransformResult {
  edits: Array<Edit>
  used: Array<string>
  preserved: Array<string>
  valid: boolean
}

export declare function uniqueStringsNative(values: Array<string>): Array<string>

export declare function writeMigrationFileNative(file: string, source: string, code: string, backup?: string | undefined | null): Promise<boolean>
