name: Validate Tailwind Patch Migration Report

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-migration-report:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run migration report checks
        uses: ./packages/tailwindcss-patch/examples/github-actions/actions/validate-migration-report
        with:
          scope: all
          report-file: .tw-patch/migrate-report.json
          validate-output-file: .tw-patch/validate-result.json

      - name: Upload validate result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tw-patch-validate-result
          path: .tw-patch/validate-result.json
