name: Validate Tailwind Patch Migration Report (Matrix)

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate-migration-report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        shard:
          - name: root
            report_file: .tw-patch/migrate-report-root.json
          - name: apps
            report_file: .tw-patch/migrate-report-apps.json
          - name: packages
            report_file: .tw-patch/migrate-report-packages.json

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run migration report checks (${{ matrix.shard.name }})
        uses: ./packages/tailwindcss-patch/examples/github-actions/actions/validate-migration-report
        with:
          scope: ${{ matrix.shard.name }}
          shard-name: ${{ matrix.shard.name }}
          report-file: ${{ matrix.shard.report_file }}
          validate-output-file: .tw-patch/validate-result-${{ matrix.shard.name }}.json

      - name: Upload validate result (${{ matrix.shard.name }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tw-patch-validate-result-${{ matrix.shard.name }}
          path: .tw-patch/validate-result-${{ matrix.shard.name }}.json
